spring:
  h2:
    console:
      enabled: true       # H2 웹 콘솔을 사용하겠다는 의미
      path: /h2_console   # 콘솔의 경로 localhost:8080/h2_console

  datasource:
    driver-class-name: org.h2.Driver  #h2 드라이버 설정
    url: jdbc:h2:mem:testDB;MODE=MySQL
    username: sa
    password:

  jpa:
    database-platform: org.hibernate.dialect.H2Dialect
    open-in-view: false
    hibernate:
      ddl-auto: create-drop
      naming: #Table, Column naming
        physical-strategy: org.hibernate.boot.model.naming.PhysicalNamingStrategyStandardImpl
    properties:
      hibernate:
        show-sql: true
        format_sql: true
        default_batch_fetch_size: 100

  messages:
    basename: messages

server:
  port: 8080